"""The read-back before anything is created, and the rename loop after a collision.

Three kinds of test here.

WHAT THE USER HEARS. The intro must contain the owner, the EXACT slug and the
visibility, and the capability sentence must be last — because that is the part
that says what can and cannot be undone, and nothing may follow it.

WHAT THE CHANNELS DO WITH IT. ``jarvis.telegram.channel`` reads a
``confirm_effect`` as a boolean and REFUSES a presentation whose options it does
not recognise. So the answer a real channel would build is built here, through
that channel's own ``build_answer``, and fed back in. If the option labels ever
drift, this fails rather than the Telegram bot at 1am.

WHAT HAPPENS WHEN NOBODY ANSWERS. Creation is irreversible, so the read-back must
age into a DENIAL and never into consent.
"""

from __future__ import annotations

import sqlite3
from collections.abc import Iterator
from pathlib import Path

import pytest

from jarvis import requests as rq
from jarvis.db import connect, migrate
from jarvis.github import scopes
from jarvis.github.transport import FakeTransport
from jarvis.ids import now
from jarvis.project import confirm
from jarvis.telegram import channel as tg

OWNER = "Efkrdnz"
JOB = "job_projecttests"


@pytest.fixture
def con(tmp_path: Path) -> Iterator[sqlite3.Connection]:
    c = connect(tmp_path / "jarvis.db")
    migrate(c)
    c.execute(
        """INSERT INTO jobs (id, kind, title, state, created_at, updated_at, created_by)
           VALUES (?, 'claude_code', 'comment watcher', 'running', ?, ?, 'test')""",
        (JOB, now(), now()),
    )
    yield c
    c.close()


def caps_of(*, scopes_held: tuple[str, ...] | None = ("repo",)) -> scopes.Capabilities:
    """A real matrix, read the way production reads it: out of a response header."""
    return scopes.capabilities(FakeTransport(login=OWNER, scopes=scopes_held))


# ───────────────────────────── the read-back ─────────────────────────────


def test_the_readback_says_owner_exact_slug_and_visibility() -> None:
    line = confirm.readback(
        owner=OWNER, name="comment-watcher", spoken_name="comment watcher", caps=caps_of()
    )
    assert f"github.com/{OWNER}/comment-watcher" in line
    assert f"Owner {OWNER}" in line
    assert "repository name comment-watcher" in line
    assert "private and empty" in line


def test_the_readback_ends_with_what_can_and_cannot_be_undone() -> None:
    """The capability sentence is generated by jarvis.github.scopes and goes LAST."""
    caps = caps_of()
    line = confirm.readback(
        owner=OWNER, name="comment-watcher", spoken_name="comment watcher", caps=caps
    )
    assert line.endswith(scopes.spoken_capability_line(caps, slug="comment-watcher"))
    assert "can't delete it" in line
    assert "zz-abandoned-comment-watcher" in line


def test_a_slug_the_user_could_not_have_predicted_is_spelled_out() -> None:
    """Turkish is exactly this case: "İstanbul" does not obviously become "istanbul"."""
    line = confirm.readback(
        owner=OWNER, name="istanbul-takip", spoken_name="İstanbul Takip", caps=caps_of()
    )
    assert "spelled i s t a n b u l, hyphen, t a k i p" in line

    plain = confirm.readback(
        owner=OWNER, name="comment-watcher", spoken_name="comment watcher", caps=caps_of()
    )
    assert "spelled" not in plain


def test_there_is_no_readback_for_a_public_repository() -> None:
    """The harm is engineered down or it is not created at all; there is no third wording."""
    with pytest.raises(ValueError, match="private and empty"):
        confirm.readback(
            owner=OWNER,
            name="comment-watcher",
            spoken_name="comment watcher",
            caps=caps_of(),
            private=False,
        )


def test_a_token_that_can_do_nothing_says_so_in_the_readback() -> None:
    """No compensation available -> the read-back must not imply one exists."""
    caps = caps_of(scopes_held=("public_repo",))
    line = confirm.readback(
        owner=OWNER, name="comment-watcher", spoken_name="comment watcher", caps=caps
    )
    assert "can't delete it" in line
    assert "nothing" in line.lower() or "not sure" in line.lower()


# ───────────────────────────── the row ─────────────────────────────


def test_the_request_is_a_confirm_effect_that_denies_on_timeout(con: sqlite3.Connection) -> None:
    req = confirm.raise_confirmation(
        con,
        owner=OWNER,
        name="comment-watcher",
        spoken_name="comment watcher",
        caps=caps_of(),
        actor="desk",
        job_id=JOB,
    )
    assert req.kind == "confirm_effect"
    assert req.state == "pending"
    assert req.on_timeout == "deny"
    assert req.reversibility == "compensatable"
    assert req.presentation["verbatim"] is True
    assert req.payload["name"] == "comment-watcher"
    assert req.payload["private"] is True
    assert req.payload["auto_init"] is False
    # The matrix that produced the wording is stored with it, so "why did it say
    # that" is answerable from the row six months later.
    assert req.payload["capabilities"]["delete"] == "no"
    assert req.payload["capabilities"]["source"] == "x-oauth-scopes"


def test_asking_twice_about_the_same_repository_finds_the_same_row(
    con: sqlite3.Connection,
) -> None:
    kw = {
        "owner": OWNER,
        "spoken_name": "comment watcher",
        "caps": caps_of(),
        "actor": "desk",
        "job_id": JOB,
    }
    first = confirm.raise_confirmation(con, name="comment-watcher", **kw)  # type: ignore[arg-type]
    again = confirm.raise_confirmation(con, name="comment-watcher", **kw)  # type: ignore[arg-type]
    assert again.id == first.id
    other = confirm.raise_confirmation(con, name="comment-watcher-2", **kw)  # type: ignore[arg-type]
    assert other.id != first.id
    # And the activity log says the user was asked twice, not three times.
    kinds = [r["kind"] for r in con.execute("SELECT kind FROM events ORDER BY seq")]
    assert kinds.count("request.created") == 2


def test_an_unanswered_readback_becomes_a_denial_and_never_consent(
    con: sqlite3.Connection,
) -> None:
    req = confirm.raise_confirmation(
        con,
        owner=OWNER,
        name="comment-watcher",
        spoken_name="comment watcher",
        caps=caps_of(),
        actor="desk",
        job_id=JOB,
        expires_in_s=1,
    )
    rq.expire_due(con, now_ts="2999-01-01T00:00:00.000Z")
    decided = confirm.decision(con, req.id)
    assert decided.kind == "cancel"
    assert not decided.approved


# ───────────────────────────── the decision ─────────────────────────────


def _answer_as_telegram_would(
    con: sqlite3.Connection,
    req: rq.Request,
    *,
    picks: tuple[int, ...] = (),
    free_text: str | None = None,
) -> None:
    """Answer through the CHANNEL's own builder, not through a hand-made dict.

    This is the whole point of the test: if the presentation stops being one the
    channel can read, ``build_answer`` raises here instead of in the bot.
    """
    answer = tg.build_answer(req, picks=picks, free_text=free_text)
    assert rq.answer_request(con, req.id, answer, "telegram", "button")


def _pending(con: sqlite3.Connection) -> rq.Request:
    return confirm.raise_confirmation(
        con,
        owner=OWNER,
        name="comment-watcher",
        spoken_name="comment watcher",
        caps=caps_of(),
        actor="desk",
        job_id=JOB,
    )


def test_a_pending_request_is_pending_and_not_a_no(con: sqlite3.Connection) -> None:
    req = _pending(con)
    decided = confirm.decision(con, req.id)
    assert decided.kind == "pending"
    assert not decided.approved


def test_tapping_yes_is_a_create(con: sqlite3.Connection) -> None:
    req = _pending(con)
    _answer_as_telegram_would(con, req, picks=(1,))
    decided = confirm.decision(con, req.id)
    assert decided.kind == "create"
    assert decided.approved
    assert decided.name == "comment-watcher"


def test_tapping_no_is_a_cancel(con: sqlite3.Connection) -> None:
    req = _pending(con)
    _answer_as_telegram_would(con, req, picks=(2,))
    decided = confirm.decision(con, req.id)
    assert decided.kind == "cancel"
    assert not decided.approved


def test_saying_another_name_is_a_rename_and_never_an_approval(
    con: sqlite3.Connection,
) -> None:
    """Free text on a yes/no question means "something other than what was offered"."""
    req = _pending(con)
    _answer_as_telegram_would(con, req, free_text="call it Yorum İzleyici")
    decided = confirm.decision(con, req.id)
    assert decided.kind == "rename"
    assert not decided.approved
    assert decided.spoken_name == "call it Yorum İzleyici"
    assert decided.name == "call-it-yorum-izleyici"


def test_free_text_that_is_not_a_usable_name_is_unclear_rather_than_a_guess(
    con: sqlite3.Connection,
) -> None:
    req = _pending(con)
    _answer_as_telegram_would(con, req, free_text="...")
    decided = confirm.decision(con, req.id)
    assert decided.kind == "unclear"
    assert not decided.approved
    assert decided.spoken


def test_an_answer_that_says_yes_and_no_at_once_decides_nothing(
    con: sqlite3.Connection,
) -> None:
    """A hand-written or buggy channel must not be able to invert consent."""
    req = _pending(con)
    assert rq.answer_request(
        con,
        req.id,
        {"approved": True, "answers": {confirm.CONFIRM_QUESTION: confirm.NO_LABEL}},
        "hud",
        "button",
    )
    decided = confirm.decision(con, req.id)
    assert decided.kind == "unclear"
    assert not decided.approved


def test_the_affirmative_is_option_one_because_a_channel_depends_on_it() -> None:
    """The existing Telegram channel refuses any other arrangement, loudly."""
    pres = confirm.confirmation_presentation(
        owner=OWNER, name="comment-watcher", spoken_name="comment watcher", caps=caps_of()
    )
    labels = [item["label"] for item in pres["items"]]
    assert labels[tg.APPROVE_INDEX - 1] in tg.AFFIRMATIVE_LABELS
    assert labels[1] in tg.NEGATIVE_LABELS
    assert pres["dtmf_map"] == {"1": 1, "2": 2}


# ───────────────────────────── the rename loop ─────────────────────────────


def test_the_rename_question_offers_no_options_and_no_suffix(con: sqlite3.Connection) -> None:
    req = confirm.raise_rename(
        con,
        owner=OWNER,
        rejected="comment-watcher",
        reason="There is already a repository called comment-watcher under Efkrdnz.",
        actor="desk",
        job_id=JOB,
    )
    assert req.kind == "free_text"
    assert req.presentation["items"] == []
    assert req.presentation["allows_free_text"] is True
    assert "comment-watcher-2" not in req.presentation["intro"]
    # Nothing has been created, so the question may simply wait for an answer.
    assert req.on_timeout == "defer"


def test_the_new_name_comes_back_in_the_users_own_words(con: sqlite3.Connection) -> None:
    req = confirm.raise_rename(
        con,
        owner=OWNER,
        rejected="comment-watcher",
        reason="Taken.",
        actor="desk",
        job_id=JOB,
    )
    _answer_as_telegram_would(con, req, free_text="yorum izleyici")
    answered = rq.get_request(con, req.id)
    assert answered is not None
    assert confirm.spoken_name_from(answered) == "yorum izleyici"


def test_a_second_collision_is_a_second_row_rather_than_a_silent_suffix(
    con: sqlite3.Connection,
) -> None:
    first = confirm.raise_rename(
        con, owner=OWNER, rejected="comment-watcher", reason="Taken.", actor="desk", job_id=JOB
    )
    second = confirm.raise_rename(
        con, owner=OWNER, rejected="yorum-izleyici", reason="Taken too.", actor="desk", job_id=JOB
    )
    assert second.id != first.id
